
## application YAML Template - UAT environment

server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: "${RDS_PASSWORD}"
    dbcp2:
      validation-query: SELECT 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    mapping-resources:
      - hibernate/Patient.hbm.xml
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

message: PROD Environment

