
## application YAML Template - dev environment

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/validtest
    username: postgres
    password: 123456
    dbcp2:
      validation-query: SELECT 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    mapping-resources:
      - hibernate/Patient.hbm.xml
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.type: trace
logging.level.org.hibernate.stat: debug

message: DEV Environment
